-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-23 21:16:20 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE analize (
    id_analiza          NUMBER NOT NULL,
    data_analiza        DATE NOT NULL,
    pacienti_id_pacient NUMBER NOT NULL
);

ALTER TABLE analize ADD CONSTRAINT analize_pk PRIMARY KEY ( id_analiza );

CREATE TABLE analize_valori (
    analize_id_analiza NUMBER NOT NULL,
    valori_id_valoare  NUMBER NOT NULL
);

ALTER TABLE analize_valori ADD CONSTRAINT analize_valori_pk PRIMARY KEY ( analize_id_analiza,
                                                                          valori_id_valoare );

CREATE TABLE consultatii (
    id_consultatie      NUMBER NOT NULL,
    data_consultatiei   DATE NOT NULL,
    pacienti_id_pacient NUMBER NOT NULL,
    medici_id_medic     NUMBER NOT NULL,
    nume_consultatie    VARCHAR2(64) NOT NULL
);

ALTER TABLE consultatii ADD CONSTRAINT consultatii_pk PRIMARY KEY ( id_consultatie );

CREATE TABLE consultatii_preturi (
    consultatii_id_consultatie NUMBER NOT NULL,
    preturi_id_pret            NUMBER NOT NULL
);

ALTER TABLE consultatii_preturi ADD CONSTRAINT consultatii_preturi_pk PRIMARY KEY ( consultatii_id_consultatie,
                                                                                    preturi_id_pret );

CREATE TABLE fise_medicale (
    id_fisa_medicala       NUMBER NOT NULL,
    data_investigatie      DATE NOT NULL,
    descriere_investigatie VARCHAR2(512) NOT NULL,
    pacienti_id_pacient    NUMBER NOT NULL
);

CREATE UNIQUE INDEX fise_medicale__idx ON
    fise_medicale (
        pacienti_id_pacient
    ASC );

ALTER TABLE fise_medicale ADD CONSTRAINT fise_medicale_pk PRIMARY KEY ( id_fisa_medicala );

CREATE TABLE medici (
    id_medic                     NUMBER NOT NULL,
    nume_medic                   VARCHAR2(64) NOT NULL,
    prenume_medic                VARCHAR2(64) NOT NULL,
    data_nastere_medic           DATE NOT NULL,
    cnp_medic          VARCHAR2(16) NOT NULL,
    telefon_medic                VARCHAR2(16) NOT NULL,
    email_medic                  VARCHAR2(128) NOT NULL,
    specializari_id_specializare NUMBER NOT NULL,
    parola_medic                 VARCHAR2(64) NOT NULL
);

ALTER TABLE medici ADD CONSTRAINT medici_pk PRIMARY KEY ( id_medic );

ALTER TABLE medici ADD CONSTRAINT medici_email_medic_un UNIQUE ( email_medic );

CREATE TABLE pacienti (
    id_pacient           NUMBER NOT NULL,
    nume_pacient         VARCHAR2(64) NOT NULL,
    prenume_pacient      VARCHAR2(64) NOT NULL,
    data_nastere_pacient DATE NOT NULL,
    cnp_pacient          VARCHAR2(16) NOT NULL,
    sex_pacient          VARCHAR2(16) NOT NULL,
    greutate_pacient     NUMBER(5, 2) NOT NULL,
    inaltime_pacient     NUMBER(5, 2) NOT NULL,
    asigurat             CHAR(1) NOT NULL,
    telefon_pacient      VARCHAR2(16) NOT NULL,
    email_pacient        VARCHAR2(128),
    abonament_pacient    CHAR(1) NOT NULL
);

ALTER TABLE pacienti
    ADD CONSTRAINT only_y_n CHECK ( asigurat IN ( 'N', 'Y' ) );

ALTER TABLE pacienti
    ADD CONSTRAINT only_y_n_2 CHECK ( abonament_pacient IN ( 'N', 'Y' ) );

ALTER TABLE pacienti ADD CONSTRAINT pacienti_pk PRIMARY KEY ( id_pacient );

ALTER TABLE pacienti ADD CONSTRAINT pacienti_email_pacient_un UNIQUE ( email_pacient );

CREATE TABLE preturi (
    id_pret NUMBER NOT NULL,
    valoare NUMBER NOT NULL
);

ALTER TABLE preturi ADD CONSTRAINT preturi_pk PRIMARY KEY ( id_pret );

CREATE TABLE specializari (
    id_specializare   NUMBER NOT NULL,
    nume_specializare VARCHAR2(64) NOT NULL
);

ALTER TABLE specializari ADD CONSTRAINT specializari_pk PRIMARY KEY ( id_specializare );

CREATE TABLE valori (
    id_valoare       NUMBER NOT NULL,
    nume_valoare     VARCHAR2(32) NOT NULL,
    rezultat_valoare NUMBER NOT NULL
);

ALTER TABLE valori ADD CONSTRAINT valori_pk PRIMARY KEY ( id_valoare );

ALTER TABLE analize
    ADD CONSTRAINT analize_pacienti_fk FOREIGN KEY ( pacienti_id_pacient )
        REFERENCES pacienti ( id_pacient );

ALTER TABLE analize_valori
    ADD CONSTRAINT analize_valori_analize_fk FOREIGN KEY ( analize_id_analiza )
        REFERENCES analize ( id_analiza );

ALTER TABLE analize_valori
    ADD CONSTRAINT analize_valori_valori_fk FOREIGN KEY ( valori_id_valoare )
        REFERENCES valori ( id_valoare );

ALTER TABLE consultatii_preturi
    ADD CONSTRAINT consult_preturi_consultatii_fk FOREIGN KEY ( consultatii_id_consultatie )
        REFERENCES consultatii ( id_consultatie );

ALTER TABLE consultatii
    ADD CONSTRAINT consultatii_medici_fk FOREIGN KEY ( medici_id_medic )
        REFERENCES medici ( id_medic );

ALTER TABLE consultatii
    ADD CONSTRAINT consultatii_pacienti_fk FOREIGN KEY ( pacienti_id_pacient )
        REFERENCES pacienti ( id_pacient );

ALTER TABLE consultatii_preturi
    ADD CONSTRAINT consultatii_preturi_preturi_fk FOREIGN KEY ( preturi_id_pret )
        REFERENCES preturi ( id_pret );

ALTER TABLE fise_medicale
    ADD CONSTRAINT fise_medicale_pacienti_fk FOREIGN KEY ( pacienti_id_pacient )
        REFERENCES pacienti ( id_pacient );

ALTER TABLE medici
    ADD CONSTRAINT medici_specializari_fk FOREIGN KEY ( specializari_id_specializare )
        REFERENCES specializari ( id_specializare );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             1
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
