select * from consultatii;
select * from preturi;
select * from pacienti;
select * from medici;
select * from specializari;
select * from analize;
select * from valori;
commit;

//preturi
INSERT INTO Preturi (ID_PRET, pret_fara_abonament, pret_cu_abonament)
VALUES (PRET_SEQ.NEXTVAL, 180, 120);
INSERT INTO Preturi (ID_PRET, pret_fara_abonament, pret_cu_abonament)
VALUES (PRET_SEQ.NEXTVAL, 250, 200);

//consultatii
INSERT INTO consultatii (id_consultatie, data_consultatiei, pacienti_id_pacient, medici_id_medic, nume_consultatie, preturi_id_pret)
VALUES (CONSULTATIE_SEQ.NEXTVAL, TO_DATE('2024-03-10', 'YYYY-MM-DD'), 2, 2, 'Consultatie Cardiologie', 2);
INSERT INTO consultatii (id_consultatie, data_consultatiei, pacienti_id_pacient, medici_id_medic, nume_consultatie, preturi_id_pret)
VALUES (CONSULTATIE_SEQ.NEXTVAL, TO_DATE('2024-08-10', 'YYYY-MM-DD'), 1, 1, 'Consultatie Dermatologie', 1);

//analize
INSERT INTO analize (id_analiza, data_analiza, pacienti_id_pacient)
VALUES (analiza_seq.nextval, TO_DATE('2024-06-10', 'YYYY-MM-DD'), 2);
INSERT INTO analize (id_analiza, data_analiza, pacienti_id_pacient)
VALUES (analiza_seq.nextval, TO_DATE('2024-05-09', 'YYYY-MM-DD'), 3);

//valori
INSERT INTO valori (ID_VALOARE,  NUME_VALOARE, REZULTAT_VALOARE)
VALUES (VALOARE_SEQ.NEXTVAL, 'Insulina', 120.0);
INSERT INTO valori (ID_VALOARE,  NUME_VALOARE, REZULTAT_VALOARE)
VALUES (VALOARE_SEQ.NEXTVAL, 'Calciu', 301.0);
INSERT INTO valori (ID_VALOARE,  NUME_VALOARE, REZULTAT_VALOARE)
VALUES (VALOARE_SEQ.NEXTVAL, 'Fier', 220.0);

//valori analize
INSERT INTO analize_valori (ANALIZE_ID_ANALIZA, VALORI_ID_VALOARE)
VALUES (1,1);
INSERT INTO analize_valori (ANALIZE_ID_ANALIZA, VALORI_ID_VALOARE)
VALUES (2,2);

//diagnostice
INSERT INTO diagnostice (ID_DIAGNOSTIC, DATA_DIAGNOSTIC, NUME_DIAGNOSTIC, PACIENTI_ID_PACIENT)
values (DIAGNOSTIC_SEQ.NEXTVAL, TO_DATE('2021-04-01', 'YYYY-MM-DD'), 'Psoriasis', 2);
INSERT INTO diagnostice (ID_DIAGNOSTIC, DATA_DIAGNOSTIC, NUME_DIAGNOSTIC, PACIENTI_ID_PACIENT)
values (DIAGNOSTIC_SEQ.NEXTVAL, TO_DATE('2019-02-08', 'YYYY-MM-DD'), 'Tahicardie', 1);

//specializari
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Cardiologie');
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Dermatologie');
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Neurochirurgie');
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Ginecologie');
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Ortopedie');
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Oncologie');
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Oftalmologie');
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Psihiatrie');
INSERT INTO specializari (id_specializare, nume_specializare)
VALUES (SPECIALIZARE_SEQ.NEXTVAL, 'Urologie');









REM INSERTING into IONE.SPECIALIZARI
SET DEFINE OFF;
Insert into IONE.SPECIALIZARI (ID_SPECIALIZARE,NUME_SPECIALIZARE) values (43,'Ginecologie');
Insert into IONE.SPECIALIZARI (ID_SPECIALIZARE,NUME_SPECIALIZARE) values (44,'Neurologie');
Insert into IONE.SPECIALIZARI (ID_SPECIALIZARE,NUME_SPECIALIZARE) values (45,'Ortopedie');
Insert into IONE.SPECIALIZARI (ID_SPECIALIZARE,NUME_SPECIALIZARE) values (46,'Oncologie');
Insert into IONE.SPECIALIZARI (ID_SPECIALIZARE,NUME_SPECIALIZARE) values (41,'Cardiologie');
Insert into IONE.SPECIALIZARI (ID_SPECIALIZARE,NUME_SPECIALIZARE) values (42,'Oftalmologie');
Insert into IONE.SPECIALIZARI (ID_SPECIALIZARE,NUME_SPECIALIZARE) values (47,'Psihiatrie');
Insert into IONE.SPECIALIZARI (ID_SPECIALIZARE,NUME_SPECIALIZARE) values (48,'Urologie');
REM INSERTING into IONE.VALORI
SET DEFINE OFF;
Insert into IONE.VALORI (ID_VALOARE,NUME_VALOARE,REZULTAT_VALOARE) values (44,'Glicemie',30);
REM INSERTING into IONE.PRETURI
SET DEFINE OFF;
Insert into IONE.PRETURI (ID_PRET,VALOARE) values (47,150);
Insert into IONE.PRETURI (ID_PRET,VALOARE) values (45,200);
Insert into IONE.PRETURI (ID_PRET,VALOARE) values (46,120);
REM INSERTING into IONE.MEDICI
SET DEFINE OFF;
Insert into IONE.MEDICI (ID_MEDIC,NUME_MEDIC,PRENUME_MEDIC,DATA_NASTERE_MEDIC,CNP_MEDIC,TELEFON_MEDIC,EMAIL_MEDIC,SPECIALIZARI_ID_SPECIALIZARE,PAROLA_MEDIC) values (61,'Vornicu','Andrei',to_date('22-JUN-95','DD-MON-RR'),'1950622097621','0639485716','vornicu@gmail.com',43,'$2a$10$9ya/8jY4yhVo6ZEZaIBpKe0unFfjmvsVJ1MGtnVEDn/x2sTBveG6K');
Insert into IONE.MEDICI (ID_MEDIC,NUME_MEDIC,PRENUME_MEDIC,DATA_NASTERE_MEDIC,CNP_MEDIC,TELEFON_MEDIC,EMAIL_MEDIC,SPECIALIZARI_ID_SPECIALIZARE,PAROLA_MEDIC) values (41,'Adam','Claudiu',to_date('10-JUN-02','DD-MON-RR'),'59012094750233','0792648397','adamc@gmail.com',41,'$2a$10$pzXfXsC1ZRqwt0HqCoUmcuGXcJmilLYflSrKFhVfGGrrkBpSIsOuq');
Insert into IONE.MEDICI (ID_MEDIC,NUME_MEDIC,PRENUME_MEDIC,DATA_NASTERE_MEDIC,CNP_MEDIC,TELEFON_MEDIC,EMAIL_MEDIC,SPECIALIZARI_ID_SPECIALIZARE,PAROLA_MEDIC) values (43,'Vasilescu','Mihai',to_date('03-MAY-00','DD-MON-RR'),'5000305016280','0938495678','mihaiv@gmail.com',41,'$2a$10$TdVsZP82ZtxY77NH0bO6jOUEFu4xyPEy/IMyyX.qR0tiD1Hd4BGKi');
REM INSERTING into IONE.FISE_MEDICALE
SET DEFINE OFF;
Insert into IONE.FISE_MEDICALE (ID_FISA_MEDICALA,DATA_INVESTIGATIE,DESCRIERE_INVESTIGATIE,PACIENTI_ID_PACIENT) values (41,to_date('03-MAR-24','DD-MON-RR'),'Pacientul prezinta simptome de diabet.',45);
REM INSERTING into IONE.PACIENTI
SET DEFINE OFF;
Insert into IONE.PACIENTI (ID_PACIENT,NUME_PACIENT,PRENUME_PACIENT,DATA_NASTERE_PACIENT,CNP_PACIENT,SEX_PACIENT,GREUTATE_PACIENT,INALTIME_PACIENT,ASIGURAT,TELEFON_PACIENT,EMAIL_PACIENT,ABONAMENT_PACIENT,PAROLA_PACIENT,VARSTA_PACIENT) values (71,'Virgil','Ion',to_date('08-JUN-90','DD-MON-RR'),'1900608098206','Masculin',76,174,'Y','0784958204','virgil@gmail.com','N','$2a$10$j2akbv6TzxRARJPMjonOku3kdmF5USqdJQ8GPDsEdjSYfUf9E6DTm',32);
Insert into IONE.PACIENTI (ID_PACIENT,NUME_PACIENT,PRENUME_PACIENT,DATA_NASTERE_PACIENT,CNP_PACIENT,SEX_PACIENT,GREUTATE_PACIENT,INALTIME_PACIENT,ASIGURAT,TELEFON_PACIENT,EMAIL_PACIENT,ABONAMENT_PACIENT,PAROLA_PACIENT,VARSTA_PACIENT) values (72,'Dobre','Stela',to_date('14-FEB-94','DD-MON-RR'),'2940214044565','feminin',54,160,'Y','063984831`','dobre@gmail.com','Y','$2a$10$hrvFsjp7SmBGi.QodzZCLO6tBj/WqprkMjK8WXm0a4s3sCe0XlFeK',29);
Insert into IONE.PACIENTI (ID_PACIENT,NUME_PACIENT,PRENUME_PACIENT,DATA_NASTERE_PACIENT,CNP_PACIENT,SEX_PACIENT,GREUTATE_PACIENT,INALTIME_PACIENT,ASIGURAT,TELEFON_PACIENT,EMAIL_PACIENT,ABONAMENT_PACIENT,PAROLA_PACIENT,VARSTA_PACIENT) values (45,'Farcas','Luiza',to_date('07-MAR-03','DD-MON-RR'),'6030703440041','Feminim',75,180.3,'Y','0730975268','farcas@gmail.com','Y','$2a$10$KwQ4x.drbfWPntHuad0yD.Hw/usbGD4HGfA4/NV.nJvdAJVZuTVPO',21);
Insert into IONE.PACIENTI (ID_PACIENT,NUME_PACIENT,PRENUME_PACIENT,DATA_NASTERE_PACIENT,CNP_PACIENT,SEX_PACIENT,GREUTATE_PACIENT,INALTIME_PACIENT,ASIGURAT,TELEFON_PACIENT,EMAIL_PACIENT,ABONAMENT_PACIENT,PAROLA_PACIENT,VARSTA_PACIENT) values (46,'Vatamanu','Mihai',to_date('06-APR-01','DD-MON-RR'),'5010604317522','Masculin',90.5,188.5,'Y','0792847501','vatamanu@gmail.com','Y','$2a$10$wm7ysC5KJ7xVci2VTBvhCeIf5c9T3xNHSAnaJBWkCGhVhN.X9GUKO',23);
REM INSERTING into IONE.CONSULTATII_PRETURI
SET DEFINE OFF;
Insert into IONE.CONSULTATII_PRETURI (CONSULTATII_ID_CONSULTATIE,PRETURI_ID_PRET) values (47,47);
REM INSERTING into IONE.CONSULTATII
SET DEFINE OFF;
Insert into IONE.CONSULTATII (ID_CONSULTATIE,DATA_CONSULTATIEI,PACIENTI_ID_PACIENT,MEDICI_ID_MEDIC,NUME_CONSULTATIE) values (47,to_date('05-MAY-24','DD-MON-RR'),45,61,'Consultatie Ginecologie');
REM INSERTING into IONE.ANALIZE_VALORI
SET DEFINE OFF;
Insert into IONE.ANALIZE_VALORI (ANALIZE_ID_ANALIZA,VALORI_ID_VALOARE) values (43,44);
REM INSERTING into IONE.ANALIZE
SET DEFINE OFF;
Insert into IONE.ANALIZE (ID_ANALIZA,DATA_ANALIZA,PACIENTI_ID_PACIENT) values (43,to_date('16-SEP-24','DD-MON-RR'),45);
