create database medical_clinic;

-- Table SPECIALIZARI
CREATE TABLE SPECIALIZARI (
    ID_SPECIALIZARE INT NOT NULL AUTO_INCREMENT,
    NUME_SPECIALIZARE VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID_SPECIALIZARE)
);

-- Table VALORI
CREATE TABLE VALORI (
    ID_VALOARE INT NOT NULL AUTO_INCREMENT,
    NUME_VALOARE VARCHAR(32) NOT NULL,
    REZULTAT_VALOARE INT NOT NULL,
    PRIMARY KEY (ID_VALOARE)
);

-- Table PRETURI
CREATE TABLE PRETURI (
    ID_PRET INT NOT NULL AUTO_INCREMENT,
    PRET_FARA_ABONAMENT DECIMAL(10, 2) NOT NULL,
    PRET_CU_ABONAMENT DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_PRET)
);

-- Table MEDICI
CREATE TABLE MEDICI (
    ID_MEDIC INT NOT NULL AUTO_INCREMENT,
    NUME_MEDIC VARCHAR(64) NOT NULL,
    PRENUME_MEDIC VARCHAR(64) NOT NULL,
    DATA_NASTERE_MEDIC DATE NOT NULL,
    CNP_MEDIC VARCHAR(16) NOT NULL,
    TELEFON_MEDIC VARCHAR(16) NOT NULL,
    EMAIL_MEDIC VARCHAR(128) NOT NULL,
    SPECIALIZARI_ID_SPECIALIZARE INT NOT NULL,
    PAROLA_MEDIC VARCHAR(64) NOT NULL,
    EXPERIENTA INT,
    UNIVERSITATE VARCHAR(128),
    PRIMARY KEY (ID_MEDIC),
    UNIQUE (EMAIL_MEDIC),
    FOREIGN KEY (SPECIALIZARI_ID_SPECIALIZARE) REFERENCES SPECIALIZARI(ID_SPECIALIZARE)
);

-- Table PACIENTI
CREATE TABLE PACIENTI (
    ID_PACIENT INT NOT NULL AUTO_INCREMENT,
    NUME_PACIENT VARCHAR(64) NOT NULL,
    PRENUME_PACIENT VARCHAR(64) NOT NULL,
    DATA_NASTERE_PACIENT DATE NOT NULL,
    CNP_PACIENT VARCHAR(16) NOT NULL,
    SEX_PACIENT VARCHAR(16) NOT NULL,
    GREUTATE_PACIENT DECIMAL(5, 2) NOT NULL,
    INALTIME_PACIENT DECIMAL(5, 2) NOT NULL,
    ASIGURAT CHAR(1) NOT NULL CHECK (ASIGURAT IN ('N', 'Y')),
    TELEFON_PACIENT VARCHAR(16) NOT NULL,
    EMAIL_PACIENT VARCHAR(128) NOT NULL,
    ABONAMENT_PACIENT CHAR(1) NOT NULL CHECK (ABONAMENT_PACIENT IN ('N', 'Y')),
    PAROLA_PACIENT VARCHAR(64) NOT NULL,
    VARSTA_PACIENT INT NOT NULL,
    PRIMARY KEY (ID_PACIENT),
    UNIQUE (EMAIL_PACIENT)
);

-- Table DIAGNOSTICE
CREATE TABLE DIAGNOSTICE (
    ID_DIAGNOSTIC INT NOT NULL AUTO_INCREMENT,
    DATA_DIAGNOSTIC DATE NOT NULL,
    DESCRIERE_DIAGNOSTIC VARCHAR(512),
    NUME_DIAGNOSTIC VARCHAR(64),
    PACIENTI_ID_PACIENT INT NOT NULL,
    PRIMARY KEY (ID_DIAGNOSTIC),
    FOREIGN KEY (PACIENTI_ID_PACIENT) REFERENCES PACIENTI(ID_PACIENT)
);

-- Table CONSULTATII
CREATE TABLE CONSULTATII (
    ID_CONSULTATIE INT NOT NULL AUTO_INCREMENT,
    DATA_CONSULTATIEI DATE NOT NULL,
    PACIENTI_ID_PACIENT INT NOT NULL,
    MEDICI_ID_MEDIC INT NOT NULL,
    PRETURI_ID_PRET INT NOT NULL,
    NUME_CONSULTATIE VARCHAR(64) NOT NULL,
    RATING INT,
    FEEDBACK VARCHAR(256),
    PRIMARY KEY (ID_CONSULTATIE),
    FOREIGN KEY (PACIENTI_ID_PACIENT) REFERENCES PACIENTI(ID_PACIENT),
    FOREIGN KEY (MEDICI_ID_MEDIC) REFERENCES MEDICI(ID_MEDIC),
    FOREIGN KEY (PRETURI_ID_PRET) REFERENCES PRETURI(ID_PRET),
    UNIQUE (MEDICI_ID_MEDIC, DATA_CONSULTATIEI)
);

-- Table ANALIZE
CREATE TABLE ANALIZE (
    ID_ANALIZA INT NOT NULL AUTO_INCREMENT,
    DATA_ANALIZA DATE NOT NULL,
    PACIENTI_ID_PACIENT INT NOT NULL,
    PRIMARY KEY (ID_ANALIZA),
    FOREIGN KEY (PACIENTI_ID_PACIENT) REFERENCES PACIENTI(ID_PACIENT)
);

-- Table ANALIZE_VALORI
CREATE TABLE ANALIZE_VALORI (
    ANALIZE_ID_ANALIZA INT NOT NULL,
    VALORI_ID_VALOARE INT NOT NULL,
    PRIMARY KEY (ANALIZE_ID_ANALIZA, VALORI_ID_VALOARE),
    FOREIGN KEY (ANALIZE_ID_ANALIZA) REFERENCES ANALIZE(ID_ANALIZA),
    FOREIGN KEY (VALORI_ID_VALOARE) REFERENCES VALORI(ID_VALOARE)
);

-- Table BOLI
CREATE TABLE BOLI (
    ID_BOALA INT NOT NULL AUTO_INCREMENT,
    NUME_BOALA VARCHAR(64) NOT NULL,
    DESCRIERE_BOALA VARCHAR(1024),
    PRIMARY KEY (ID_BOALA)
);

-- Adding columns and constraints to VALORI
ALTER TABLE VALORI ADD valoare_min DECIMAL(10, 2);
ALTER TABLE VALORI ADD valoare_max DECIMAL(10, 2);

-- Adding constraints for CONSULTATII
ALTER TABLE CONSULTATII ADD CONSTRAINT consultatie_unica UNIQUE (MEDICI_ID_MEDIC, DATA_CONSULTATIEI);

